# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      
      - name: Install Packages
        run: npm install
      
      - name: Build Gatsby Site
        run: npm run build
        
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          publish-dir: './public' 
          production-branch: master
          deploy-message: '${{github.event.head_commit.message}}'
        env:
          NETLIFY_SITE_ID: '${{secrets.NETLIFY_SITE_ID}}'
          NETLIFY_AUTH_TOKEN: '${{secrets.NETLIFY_AUTH_TOKEN}}'
